services:
  - type: web
    name: postgresql-age-of-ai-presentation
    runtime: static
    rootDir: postgresql-age-of-ai
    buildCommand: npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
