import {spawnSync} from 'node:child_process';
const checks=[];
function sql(label,query,{boolean=false}={}){let r=spawnSync('psql',['-X','-A','-t','-v','ON_ERROR_STOP=1','-d',process.env.PGDATABASE||'postgres','-c',query],{encoding:'utf8',timeout:5000});let value=r.status===0?r.stdout.trim():r.stderr.trim().split('\n')[0];checks.push({label,ok:r.status===0&&(!boolean||value==='t'),value});return r.status===0?r.stdout.trim():null}
const version=sql('PostgreSQL reachable / database exists','SELECT current_setting(\'server_version\')');
if(version){sql('pgvector available',"SELECT EXISTS (SELECT 1 FROM pg_available_extensions WHERE name='vector')",{boolean:true});sql('Performance table',"SELECT to_regclass('pgai_demo.demo_users') IS NOT NULL",{boolean:true});let rowCount=sql('Performance rows',"SELECT COALESCE((SELECT reltuples::bigint FROM pg_class WHERE oid=to_regclass('pgai_demo.demo_users')),0)");if(rowCount==='0')checks.at(-1).ok=false;sql('Email index',"SELECT to_regclass('pgai_demo.demo_users_email_idx') IS NOT NULL",{boolean:true});sql('Vector table',"SELECT to_regclass('pgai_demo.chunks') IS NOT NULL",{boolean:true});}
async function probe(label,url,payload,valid,variable){if(!url){checks.push({label,ok:false,value:`set ${variable}`});return}try{let response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(process.env[variable.replace('_URL','_API_KEY')]?{Authorization:`Bearer ${process.env[variable.replace('_URL','_API_KEY')]}`}:{})},body:JSON.stringify(payload),signal:AbortSignal.timeout(5000)});let body=await response.json();checks.push({label,ok:response.ok&&valid(body),value:response.ok?'response checked':`HTTP ${response.status}`})}catch(e){checks.push({label,ok:false,value:e.message})}}
await probe('Embedding service available',process.env.EMBEDDING_URL,{model:process.env.EMBEDDING_MODEL||'nomic-embed-text',input:'preflight'},b=>Array.isArray(b.data?.[0]?.embedding||b.embedding||b.embeddings?.[0]),'EMBEDDING_URL');
await probe('RAG answer service available',process.env.LLM_URL,{model:process.env.LLM_MODEL||'local-model',messages:[{role:'user',content:'Reply OK'}],max_tokens:3,stream:false},b=>!!(b.choices?.[0]?.message?.content||b.message?.content||b.response),'LLM_URL');
checks.forEach(c=>console.log(`${c.ok?'✓':'✗'} ${c.label}${c.value?` — ${c.value}`:''}`));
if(!version)console.log('Start PostgreSQL and set PGDATABASE / PGHOST / PGUSER as needed. Prepared presentation mode works without services.');
if(checks.some(c=>!c.ok))process.exitCode=1;
