import {advancedCurriculum} from './curriculum-advanced.js';
// Original zero-to-hero study route. One presentation screen can contain several lessons.
// Each lesson names the model, the mechanism, a runnable or inspectable example, and a production decision.
const P='https://www.postgresql.org/docs/current/';
const S='https://supabase.com/docs/guides/';
const V='https://github.com/pgvector/pgvector/blob/master/README.md';
const lesson=(title,model,mechanics,sql,decision,pitfall,source)=>({title,model,mechanics,sql,decision,pitfall,source});
export const curriculum={
opening:[
lesson('The whole data journey','A database is a running system that turns requests into durable, queryable state. A table is only one part of it.','A client connects; PostgreSQL parses and plans SQL, executes it against pages and indexes, checks transaction visibility, and may log a write before acknowledging commit.','SELECT current_database(), current_user, version();','For each architecture box, ask what guarantee it gives and which resource it consumes.','An attractive architecture diagram is not evidence that its latency, consistency or recovery behavior is correct.',P+'tutorial.html')],
why:[
lesson('Why a database exists','A file stores bytes. A database adds a data model, concurrent access, constraints, queries, recovery and operational tools.','PostgreSQL coordinates transactions and uses WAL to recover committed changes. SQL constraints protect data even when several services write to it.','CREATE TABLE orders (id bigint PRIMARY KEY, total numeric(12,2) CHECK (total >= 0));','Choose PostgreSQL when related entities, reliable writes and flexible querying are central. A cache, object store, warehouse or search system can complement it.','Choosing by popularity alone ignores access patterns, latency targets and team operations.',P+'intro-whatis.html'),
lesson('PostgreSQL versus other data systems','Choose by the shape of data and the guarantees you need. PostgreSQL is a strong default when joins, constraints and transactions are central; another engine may be a better primary store for a different workload.','Compare candidates on consistency needs, query flexibility, indexing, development skill, managed options, migration cost and operational risk. A document model can suit document-first access; a columnar warehouse suits large analytical scans; a cache suits short-lived repeat reads.','-- Write the important access patterns before selecting a database.\n-- Example: fetch a tenant order, join its lines, update stock atomically.','Run a small workload test and describe why each alternative wins or loses for that workload. Multiple systems are useful only if synchronization and operations are justified.','A product label such as “NoSQL” does not tell you its transaction, query or scaling behavior.',P+'intro-whatis.html'),
lesson('Choosing PostgreSQL honestly','PostgreSQL is an open-source relational database with JSON, text search and extension support. It is a strong general-purpose choice, not a promise to fit every workload.','Compare transactional throughput, joins, query flexibility, data volume, isolation needs, operational model and specialized search or analytics requirements.','SELECT * FROM pg_available_extensions LIMIT 10;','Start with workload tests. Keep a separate system when it solves a measured limitation rather than duplicating data by default.','“SQL versus NoSQL” is not a single feature comparison; products differ in consistency, query model and operations.',P+'intro-whatis.html')],
runtime:[
lesson('API process versus database process','The API server handles HTTP and application rules. PostgreSQL runs its own server processes and owns the data files. Both consume CPU and RAM on whichever host runs them.','A query travels over a connection. PostgreSQL backends perform query work; shared buffers cache pages; the operating system and storage serve misses. WAL and table/index files occupy disk.','SELECT pid, state, wait_event_type FROM pg_stat_activity;','Measure API CPU and DB CPU separately. A busy API cannot be fixed by adding a database index; a saturated DB is not fixed by adding API replicas.','“The database is inside the API server” is only a deployment possibility, not the architecture.',P+'tutorial-arch.html')],
architecture:[
lesson('What happens to a SELECT','SQL describes a result. PostgreSQL chooses physical operators to obtain it.','Parsing checks syntax; analysis resolves names and types; rewriting can expand views; planning estimates paths; execution runs scans, joins and sorts. Shared buffers may supply cached pages.','EXPLAIN (VERBOSE, COSTS) SELECT * FROM users WHERE id = 42;','A query plan is an explanation of chosen work, not a fixed property of the SQL text. Plans can change with data and statistics.','The planner cost is not milliseconds; it is a relative estimate.',P+'using-explain.html'),
lesson('Connection and process lifecycle','A session is a long-lived connection. A transaction is a bounded unit of work inside a session. A query is one statement.','A client authenticates, establishes a backend session, submits statements and eventually disconnects. Too many sessions can consume memory even while idle.','SELECT state, count(*) FROM pg_stat_activity GROUP BY state;','Bound concurrent work with application pools or PgBouncer and watch wait time as well as active sessions.','Treating connections as free encourages exhaustion under request bursts.',P+'runtime-config-connection.html')],
create:[
lesson('Create your own database','A PostgreSQL server cluster holds databases; each database holds schemas; schemas organize tables, views and functions.','Start PostgreSQL, connect with psql, create a database, reconnect to it, then create schema objects. CREATE DATABASE requires sufficient privilege and is run outside a transaction block.','CREATE DATABASE learning;\n-- reconnect: psql -d learning\nCREATE SCHEMA app;\nCREATE TABLE app.users (id bigint PRIMARY KEY, name text NOT NULL);\nINSERT INTO app.users VALUES (1, \'Atif\');','Keep schema definitions in migration files so development, test and production can reproduce them.','A schema is not a separate database, and creating a table does not start a PostgreSQL server.',P+'tutorial-createdb.html'),
lesson('First psql habits','psql is a client, not the database server. Its backslash commands inspect your environment.','Use connection information to confirm the target database before edits. Describe tables and list schemas to discover what exists.','\\conninfo\n\\l\n\\dn\n\\dt app.*\n\\d app.users','Before modifying data, confirm the database, schema and role. Run dangerous edits in an explicit transaction you can inspect before COMMIT.','A missing semicolon makes psql wait for more SQL; a wrong connection can affect the wrong database.',P+'app-psql.html')],
data:[
lesson('Table, row, column and physical tuple','A table has named typed columns. Each row is one logical record. In relational language row means tuple; in PostgreSQL storage a heap tuple is a physical row version.','Constraints such as PRIMARY KEY, UNIQUE, NOT NULL, CHECK and FOREIGN KEY enforce data rules. PostgreSQL can store several physical versions of one logical row after updates.','CREATE TABLE customers (id bigint PRIMARY KEY, email text NOT NULL UNIQUE, joined_at timestamptz NOT NULL DEFAULT now());','Pick types and constraints that match the domain. Database constraints protect all writers, including scripts and future services.','A table is not merely a spreadsheet: rows have identity rules, concurrent visibility and transactional updates.',P+'ddl-basics.html'),
lesson('Types, NULL and time','Types define valid values and operations; NULL means unknown or absent, not zero or empty text.','Use bigint or identity keys as needed, numeric for exact money, text for strings, boolean for flags, timestamptz for instants, and JSONB for flexible documents. SQL uses three-valued logic with NULL.','SELECT NULL = NULL AS unknown, NULL IS NULL AS true_check;\nSELECT now() AT TIME ZONE \'UTC\';','Use explicit time zones and domain checks. Prefer structured columns for stable fields and relationships.','`WHERE column = NULL` never tests for missing values; use `IS NULL`. Floating point is usually unsuitable for exact currency.',P+'datatype.html')],
relation:[
lesson('Mathematical relation versus relationship','A relation is a set of tuples described by attributes. A foreign-key relationship is a separate integrity rule between table values.','A SQL table is the practical counterpart of a relation but can contain duplicate rows and NULL. A JOIN matches row values at query time; an FK checks that a referenced value is allowed.','CREATE TABLE agencies (id bigint PRIMARY KEY);\nCREATE TABLE donors (id bigint PRIMARY KEY, agency_id bigint REFERENCES agencies(id));','Use FKs to preserve integrity, and indexes when query patterns or parent-row updates justify them.','An FK does not store a pointer, perform the JOIN, or automatically index the referencing column.',P+'ddl-constraints.html')],
relations:[
lesson('Model one-to-many and many-to-many','One-to-many places the FK on the many side. Many-to-many uses a bridge table. One-to-one uses a UNIQUE FK.','A normalized model stores a fact once and joins it where needed; denormalization can be deliberate for measured reads but creates synchronization work.','CREATE TABLE enrollments (student_id bigint REFERENCES students(id), course_id bigint REFERENCES courses(id), PRIMARY KEY(student_id,course_id));','Decide ON DELETE behavior for each relationship and test the volume of affected rows.','CASCADE can delete far more rows than the visible parent, holding locks and generating WAL.',P+'ddl-constraints.html'),
lesson('JOINs and missing matches','INNER JOIN keeps matching pairs; LEFT JOIN keeps all left rows and uses NULL for a missing right match.','The ON clause defines matching values. Filters in WHERE can remove NULL-extended rows from an outer join, changing the result.','SELECT a.id, d.id FROM agencies a LEFT JOIN donors d ON d.agency_id = a.id;','Check cardinality: a one-to-many JOIN can multiply rows before GROUP BY or LIMIT.','A JOIN does not become fast merely because an FK exists; indexes and selectivity matter.',P+'tutorial-join.html')],
sql:[
lesson('Read SELECT in logical order','Written SQL starts with SELECT; reasoning about rows starts with FROM and JOIN, then WHERE, GROUP BY, HAVING, SELECT, ORDER BY and LIMIT.','WHERE filters input rows before grouping; HAVING filters groups. An alias created in SELECT generally cannot be used in WHERE of the same level.','SELECT agency_id, count(*) AS donors\nFROM donors\nWHERE active\nGROUP BY agency_id\nHAVING count(*) >= 5\nORDER BY donors DESC;','Confirm a query returns the right rows before optimizing it. Avoid SELECT * when you need only a few columns.','A row count after a JOIN can differ from the source table count.',P+'sql-select.html'),
lesson('Subqueries and CTEs','A subquery is a query inside another query. A common table expression (WITH) gives a named intermediate result, making multi-step logic easier to read.','A correlated subquery depends on values from the outer row; an uncorrelated one can stand alone. PostgreSQL may inline or materialize a CTE depending on semantics and planner choice, so inspect EXPLAIN instead of assuming it is a cache.','WITH donor_totals AS (\n  SELECT agency_id,count(*) AS n FROM donors GROUP BY agency_id\n)\nSELECT a.id,coalesce(t.n,0) FROM agencies a\nLEFT JOIN donor_totals t ON t.agency_id=a.id;','Use a CTE for clarity or reuse inside a statement, then check whether its plan performs well on representative data.','Nested SQL is not automatically slow, and a CTE does not automatically materialize or improve performance.',P+'queries-with.html'),
lesson('Aggregation and windows','GROUP BY collapses rows into groups. Window functions calculate across a partition while retaining individual rows.','A CTE names a subquery; it improves structure but is not automatically a performance optimization. A window ORDER BY and frame affect cumulative results.','SELECT id, agency_id, amount,\n       row_number() OVER (PARTITION BY agency_id ORDER BY amount DESC) AS rank_in_agency\nFROM donations;','Use windows for rankings and running totals; use GROUP BY for one row per group. Inspect the plan if sorting is costly.','A window function cannot be used directly in WHERE; wrap it in a subquery or CTE.',P+'tutorial-window.html')],
insert:[
lesson('A write before disk flush','PostgreSQL changes shared buffers and records WAL so committed changes can survive a crash before every modified heap page is flushed.','The INSERT travels through parsing, planning/execution, constraints, tuple insertion, WAL generation and commit acknowledgement. Dirty data pages can be written later.','BEGIN; INSERT INTO events(id) VALUES (1); COMMIT;','Distinguish transaction commit latency from later checkpoint and background I/O.','WAL is not simply “a second copy of the table”; it records changes for recovery.',P+'wal-intro.html'),
lesson('Write, change and return rows','INSERT, UPDATE and DELETE are statements that run within transactions. RETURNING exposes affected rows without a second read.','ON CONFLICT uses a unique constraint or unique index to define the conflict. COPY or batched INSERT suits bulk loading better than a network round trip per row.','INSERT INTO users(id,email) VALUES (1,\'a@example.test\')\nON CONFLICT (id) DO UPDATE SET email=EXCLUDED.email\nRETURNING id,email;','For high-volume changes, batch work and watch WAL, lock duration, index maintenance and autovacuum.','UPDATE or DELETE without a WHERE clause affects all qualifying rows. Check the target and affected count.',P+'dml.html'),
],
transactions:[
lesson('ACID is four different guarantees','Atomicity groups changes; consistency depends on declared rules and correct application logic; isolation controls concurrent observations; durability protects committed state.','BEGIN opens a transaction. COMMIT makes its changes durable and visible to suitable future snapshots. ROLLBACK abandons them. Savepoints allow partial rollback within one transaction.','BEGIN;\nUPDATE accounts SET balance=balance-2000 WHERE id=1;\nUPDATE accounts SET balance=balance+2000 WHERE id=2;\nCOMMIT;','Check invariant conditions and concurrent access; one transaction alone does not eliminate every race.','“The database guarantees business consistency” overstates ACID if the business invariant is not encoded or checked.',P+'tutorial-transactions.html'),
lesson('Isolation levels and anomalies','READ COMMITTED gives each statement a fresh snapshot. REPEATABLE READ keeps a transaction snapshot. SERIALIZABLE aims for an outcome equivalent to some serial order.','Higher isolation can detect conflicts and require application retries. Row locks can protect a read-modify-write sequence when appropriate.','BEGIN ISOLATION LEVEL SERIALIZABLE;\n-- perform related reads and writes\nCOMMIT;','Choose the weakest isolation that preserves the actual invariant, then test concurrent cases and retry transient serialization failures.','Isolation does not mean “no waiting”; writers may still block or deadlock.',P+'transaction-iso.html')],
concurrency:[
lesson('Two writers and one reader','Two UPDATEs of the same row conflict. A normal SELECT can usually read a committed version without waiting for that row lock.','T1 updates and retains a row-level lock until it ends. T2 waits, then rechecks the row. Under READ COMMITTED a new SELECT statement uses a new snapshot.','SELECT pid,state,wait_event_type,wait_event,now()-xact_start AS transaction_age\nFROM pg_stat_activity WHERE xact_start IS NOT NULL;','Keep transactions short and measure lock waits and transaction age. The duration depends on workload and application behavior; there is no universal “usual transaction time.”','A plain SELECT and SELECT FOR UPDATE have different locking behavior.',P+'explicit-locking.html'),
lesson('Deadlocks and safe retries','A deadlock is a cycle: T1 holds A and wants B while T2 holds B and wants A. PostgreSQL aborts one transaction to break it.','Consistent lock ordering reduces deadlocks; it does not remove every possible conflict. The application must recognize retryable errors.','-- Both transfer paths should lock accounts in the same id order.\nSELECT id FROM accounts WHERE id IN (1,2) ORDER BY id FOR UPDATE;','Retry the whole transaction only when the operation is safe to retry, using idempotency where needed.','A timeout alone does not tell you which statement caused the blocking chain.',P+'explicit-locking.html')],
mvcc:[
lesson('Tuple versions and snapshots','An UPDATE normally creates a new physical row version. A snapshot decides which committed version a statement can see.','Tuple headers contain transaction metadata including xmin and xmax. Visibility considers those IDs, transaction status and the active snapshot. Old versions remain while relevant readers might need them.','SELECT xmin,xmax,id,balance FROM accounts WHERE id=1;','Long transactions and idle-in-transaction sessions can delay cleanup. Monitor them when bloat grows.','MVCC reduces read/write blocking; it does not mean PostgreSQL has no locks.',P+'mvcc-intro.html')],
slow:[
lesson('Why data growth changes the plan','One returned row may require examining many rows or pages. Selectivity, row width, cache state and statistics determine cost.','Sequential scans are efficient when much of a table is needed. Index lookups help selective predicates but can add random heap fetches. The planner compares alternatives.','EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM demo_users WHERE email=\'user500000@example.test\';','Capture the exact query and representative data before changing schema. Compare actual time, rows and buffers.','A Seq Scan is not inherently bad; it can be the cheapest path.',P+'using-explain.html')],
index:[
lesson('B-tree and access paths','An index is a second structure that maps keys toward rows. PostgreSQL can still prefer a sequential scan, bitmap scan or index-only scan.','B-tree handles equality and ranges. Composite indexes depend on leading keys and query order. Partial and expression indexes represent narrower predicates. Index-only scans need suitable index data and visibility information.','CREATE INDEX ON users (tenant_id, created_at DESC);\nCREATE INDEX ON users (lower(email));','Index high-value query patterns, then account for extra write cost, storage and maintenance.','Adding every possible index can make writes slower and enlarge backups.',P+'indexes.html'),
lesson('Choose the index family for the operator','GIN is useful for inverted search such as JSONB containment and full text; BRIN summarizes ranges; pg_trgm can support substring-like matching.','The index must support the actual operator and predicate. A B-tree on a text column does not generally make a leading-wildcard search fast.','CREATE EXTENSION IF NOT EXISTS pg_trgm;\nCREATE INDEX users_name_trgm ON users USING gin (name gin_trgm_ops);','Benchmark with realistic data. BRIN is attractive for very large physically correlated data, not random point lookups.','“An index exists” does not mean the planner can use it for the query.',P+'indexes-types.html')],
explain:[
lesson('Read an execution plan','EXPLAIN shows the chosen tree. ANALYZE executes the SQL and adds actual row counts and timing. BUFFERS adds cache and read activity.','Read child nodes first. Estimate and actual rows reveal cardinality errors. Actual rows are per loop. Rows Removed by Filter is a useful measure of rejected tuples at a scan node; cost units are not milliseconds.','EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON)\nSELECT * FROM demo_users WHERE email=\'user500000@example.test\';','Compare the same SQL before and after a change. Use representative data and account for warmed caches.','EXPLAIN ANALYZE of UPDATE, DELETE or INSERT really changes data unless wrapped and rolled back.',P+'using-explain.html'),
lesson('Planner statistics and estimates','The optimizer estimates selectivity and row counts from table statistics, not by executing every candidate plan.','ANALYZE refreshes stats. Skewed or correlated columns can make simple estimates inaccurate; extended statistics can help some patterns.','ANALYZE demo_users;\nSELECT attname,n_distinct FROM pg_stats WHERE tablename=\'demo_users\';','Fix stale or inadequate statistics when estimated and actual rows differ greatly before forcing an access path.','A fast execution on one sample does not prove the plan is stable across tenants or parameter values.',P+'planner-stats.html')],
lab:[
lesson('A repeatable performance experiment','Optimization means measure, form a hypothesis, change one thing and measure again.','Seed representative rows, ANALYZE, capture EXPLAIN (ANALYZE, BUFFERS), create a specific index, rerun the exact SQL and compare. Then test a broad predicate where an index may lose.','EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM demo_users WHERE email=\'user500000@example.test\';','Report machine, dataset size, cache state and plan along with time. Use p95 or repeated runs for production decisions.','Prepared diagrams are explanatory; only LIVE mode supplies real execution timing.',P+'performance-tips.html')],
storage:[
lesson('Pages, buffers and TOAST','A relation is stored in pages, normally 8 KB. Pages hold line pointers and physical tuple versions.','Shared buffers cache database pages; the operating system may cache them too. Wide values can be compressed or moved to TOAST storage. Index files are separate relations.','SELECT pg_size_pretty(pg_relation_size(\'demo_users\')), pg_size_pretty(pg_total_relation_size(\'demo_users\'));','Distinguish heap size from total size including indexes and TOAST. Reads can cost CPU even on buffer hits.','A row shown as one rectangle is a teaching simplification; real page layout includes headers, item identifiers and free space.',P+'storage-page-layout.html')],
vacuum:[
lesson('Dead tuples and normal VACUUM','MVCC leaves older row versions after UPDATE or DELETE. VACUUM reclaims versions that no relevant transaction can see.','Normal VACUUM makes table space reusable, maintains visibility metadata and protects against transaction ID wraparound. It usually does not shrink the file to return space to the OS.','VACUUM (VERBOSE, ANALYZE) demo_users;','Keep autovacuum enabled and watch dead tuples, old snapshots and worker progress.','VACUUM FULL rewrites the table and takes a strong lock; it is not normal routine cleanup.',P+'routine-vacuuming.html'),
lesson('Autovacuum, ANALYZE and bloat','Autovacuum runs based on table activity thresholds and scale factors. ANALYZE updates planner statistics.','A high-update table can accumulate dead versions faster than cleanup. Long transactions can prevent removal even when workers run. Bloat means extra space relative to useful data.','SELECT relname,n_live_tup,n_dead_tup,last_autovacuum,last_autoanalyze\nFROM pg_stat_user_tables ORDER BY n_dead_tup DESC;','Tune per table when measured activity justifies it; investigate blockers before increasing worker aggressiveness.','A single n_dead_tup estimate is approximate and may lag the real table state.',P+'routine-vacuuming.html')],
wal:[
lesson('WAL, checkpoints and crash recovery','PostgreSQL logs changes before the related dirty data pages must be flushed. Recovery can replay logged changes after a crash.','A checkpoint establishes a recovery starting point and moves dirty pages toward storage. The WAL stream also supports physical replication and point-in-time recovery when archived with a base backup.','SELECT pg_current_wal_lsn();\nSHOW archive_mode;','Monitor WAL retention and disk. Test restore procedures rather than assuming files imply a recoverable backup.','Replication is not a backup: it can reproduce accidental deletes and corruption.',P+'wal-intro.html'),
lesson('Backups and PITR','A backup lets you reconstruct a database after loss; PITR restores to a selected time using a base backup plus archived WAL.','Logical dumps are useful for portability and object-level restore; physical backup plus WAL supports point-in-time recovery. Recovery time and recovery point objectives determine the plan.','pg_dump -Fc learning > learning.dump\n-- Physical/PITR setup requires base backups and WAL archiving.','Practice restoring into a separate environment and record RPO/RTO.','A successful backup job is not evidence that the restore process works.',P+'backup.html')],
replication:[
lesson('Physical and logical replication','Physical standbys replay WAL and can serve read-only queries. Logical replication publishes selected table changes.','Asynchronous physical replicas may lag. Synchronous settings change commit latency and durability tradeoffs. Failover requires promoting a node and rerouting clients.','SELECT application_name,state,sent_lsn,replay_lsn\nFROM pg_stat_replication;','Send read-after-write traffic to the primary unless you have measured and handled replica lag. Test failover.','Read replicas do not automatically scale writes or replace independent backups.',P+'warm-standby.html')],
pool:[
lesson('Why a pool exists','Each database session uses resources. A pool reuses a bounded number of sessions and queues extra application work.','Session pooling holds a server session for a client session; transaction pooling can reuse server sessions between transactions but changes session-state assumptions.','SELECT state,count(*) FROM pg_stat_activity GROUP BY state;','Tune from active query time, DB CPU/RAM, connection limits and queue wait. No universal pool size exists.','A bigger pool may increase contention while apparently reducing queue length.',P+'runtime-config-connection.html')],
partition:[
lesson('Partition pruning and maintenance','A partitioned table divides one logical relation into child tables, commonly by time.','When a query predicate aligns with bounds, PostgreSQL can skip irrelevant partitions. Inserts route to the matching child. Local indexes and maintenance still need planning.','CREATE TABLE events_by_year(id bigint, created_at date) PARTITION BY RANGE(created_at);\nCREATE TABLE events_2026 PARTITION OF events_by_year FOR VALUES FROM (\'2026-01-01\') TO (\'2027-01-01\');','Use partitioning for lifecycle management and pruning on large data with a natural key. Inspect actual plans.','Partitioning is not sharding and is not an automatic speed boost for unrelated predicates.',P+'ddl-partitioning.html')],
scale:[
lesson('From one database to many','Scale only after identifying a bottleneck. Cache, replicas, partitioning, queues and sharding solve different problems.','Cache reduces repeat reads but creates invalidation rules; replicas add read capacity and lag; queues absorb asynchronous work; sharding routes independent data across database instances.','-- Example of a partition-friendly predicate\nSELECT * FROM events WHERE created_at >= DATE \'2026-01-01\';','Sharding is justified when a single primary cannot satisfy measured storage or write capacity after simpler options. Plan cross-shard queries and transactions.','“Millions of requests” alone does not specify database load: cache hit rate, query cost and write ratio matter.',P+'high-availability.html')],
deploy:[
lesson('Serverless versus managed instance versus self-host','Serverless PostgreSQL offerings can pause or resize compute; managed instances provide chosen capacity and managed operations; self-hosting provides host control with full responsibility.','For idle or bursty development, test wake latency and connection behavior. For steady production, test fixed-capacity economics, backups, availability and storage I/O. For self-hosting, plan patching, monitoring, failover and restore drills.','SELECT pg_size_pretty(pg_database_size(current_database()));\nSELECT state,count(*) FROM pg_stat_activity GROUP BY state;','A hosting decision is revisited as workload changes. Check provider-specific extension support, networking, backup and failover terms.','Serverless does not mean zero operational concerns, and managed does not mean your schema or queries are automatically fast.','https://neon.com/docs/manage/endpoints/'),
lesson('Choose hosting and size from evidence','Self-hosting, managed instances and serverless PostgreSQL change who operates the service and how compute responds to load.','Size CPU for query/concurrent work, RAM for hot pages and sorts, storage for capacity and IOPS, and connections for bounded concurrency. Load-test representative p95 latency and leave headroom.','SELECT datname,pg_size_pretty(pg_database_size(datname)) FROM pg_database;','A variable or idle workload can benefit from serverless behavior; steady workloads may suit managed fixed capacity; self-hosting gives control with operational responsibility. Validate provider-specific limits.','Do not choose by a single database-size number; 100 GB hot random reads and 100 GB cold archives need different resources.','https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.Summary.html')],
security:[
lesson('Roles, GRANT and schemas','A role may log in or group permissions. Schemas organize objects and have their own USAGE and CREATE privileges. Object ownership and grants determine operations before RLS restricts rows.','Use a restricted application role and separate migration/owner role. Grant only the tables, sequences and functions needed; default privileges can manage future objects.','CREATE ROLE app_reader LOGIN;\nGRANT USAGE ON SCHEMA app TO app_reader;\nGRANT SELECT ON app.documents TO app_reader;','Test permissions with SET ROLE or a real app connection, not a superuser session.','Granting SELECT on a table without schema USAGE can still prevent access; ownership and BYPASSRLS can bypass row policies.',P+'user-manag.html'),
lesson('Roles, grants and RLS','Authentication proves identity; privileges authorize operations; RLS adds predicates that decide which rows a role can access.','The application must establish trusted tenant context. Table owners and BYPASSRLS roles can bypass policies unless configured appropriately. Test policies using actual app roles.','ALTER TABLE documents ENABLE ROW LEVEL SECURITY;\nCREATE POLICY tenant_read ON documents FOR SELECT USING (tenant_id = current_setting(\'app.tenant_id\')::bigint);','Use least privilege, test SELECT/INSERT/UPDATE/DELETE separately, and review policy impact on plans.','RLS is not safe if client-controlled tenant IDs are trusted without identity verification.',P+'ddl-rowsecurity.html')],
views:[
lesson('View versus materialized view','A view stores a SELECT definition; a materialized view stores the result rows and may become stale.','A normal view is evaluated against underlying data when queried. REFRESH MATERIALIZED VIEW recomputes the stored result. Materialized views can have indexes.','CREATE VIEW active_users AS SELECT id FROM users WHERE active;\nCREATE MATERIALIZED VIEW daily_counts AS SELECT day,count(*) FROM orders GROUP BY day;\nREFRESH MATERIALIZED VIEW daily_counts;','Use views for reusable interfaces and materialized views when precomputation outweighs refresh cost and staleness. Review security_invoker behavior for RLS.','A normal view is not a cache, and a materialized view is not automatically up to date.',P+'rules-materializedviews.html'),
lesson('Functions and triggers','A function packages database logic; a trigger runs on a table event.','Functions can support reusable queries or invariants. Triggers can maintain audit columns or derived data but hide work from callers. Security definer functions need careful search_path and privilege review.','CREATE FUNCTION touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at=now(); RETURN NEW; END $$;','Use declarative constraints first. Keep triggers small, documented and tested under bulk writes.','A trigger can turn one visible statement into many hidden writes and extra latency.',P+'triggers.html')],
supabase:[
lesson('What Supabase builds on PostgreSQL','Supabase uses PostgreSQL as the data core and provides Auth, API, Realtime, Storage, Edge Functions and Studio around it.','Auth stores identities in an auth schema and issues tokens; PostgREST exposes database objects; RLS restricts rows. Realtime can consume change streams. Storage keeps object metadata in Postgres while file bytes use object storage. Edge Functions run outside the DB.','SELECT schemaname,tablename,rowsecurity FROM pg_tables WHERE schemaname=\'public\';','Treat each service boundary separately: client token, API grants, RLS policy, storage policy and function secrets all matter.','Supabase is not a different database engine, and enabling Auth does not automatically make every public table safe.',S+'getting-started/architecture'),
lesson('Direct client access and RLS','A browser can call an auto-generated API safely only when exposed tables and functions have the intended privileges and policies.','Authenticated and anonymous roles are distinct. Policy expressions participate in queries; views created with owner privileges can change RLS behavior. Service roles should remain server-side.','CREATE POLICY own_rows ON documents FOR SELECT TO authenticated USING (owner_id = auth.uid());','Test as anon and authenticated users, including negative cases and joins. Measure policy performance on large tables.','Never ship a service-role key to a browser.',S+'database/postgres/row-level-security')],
extensions:[
lesson('Extensions and operational control','Extensions install database objects such as types, functions, operators and index methods; the server must have their files available.','CREATE EXTENSION enables an installed extension in a database. Managed providers decide which extensions and versions they support. pg_trgm, PostGIS and vector serve different needs.','SELECT name,installed_version FROM pg_available_extensions WHERE name IN (\'pg_trgm\',\'postgis\',\'vector\');','Check version compatibility, privileges, upgrade path and provider support before relying on an extension.','CREATE EXTENSION cannot download arbitrary extension code into a managed server.',P+'sql-createextension.html')],
jsonsearch:[
lesson('Relational columns, JSONB and text search','Use typed columns for stable keys and constraints; JSONB for flexible document fields; full-text search for language-aware word matching.','GIN can index JSONB containment and tsvector search. pg_trgm supports some substring and similarity patterns. B-tree suits exact/range access, not every LIKE pattern.','CREATE INDEX docs_json_idx ON documents USING gin(metadata);\nCREATE INDEX docs_text_idx ON documents USING gin(to_tsvector(\'english\',body));','Choose the operator and index together. Keep important join keys as columns even if a JSONB payload also exists.','JSONB is not “schema-free correctness”; validation and query contracts still exist.',P+'datatype-json.html')],
embeddings:[
lesson('What an embedding is','An embedding model maps input text to a numeric vector. A distance metric ranks vectors; it does not prove factual truth.','The query and stored chunks must use the same model and compatible dimensions. Chunk boundaries and metadata filtering affect retrieval. A 2D diagram is an analogy for a high-dimensional space.','-- Example only; real values come from an embedding model.\nSELECT \'[0.1,0.2,0.3]\'::vector;','Evaluate recall on real questions. Version model and chunking strategy so re-embedding is possible.','A visually nearby point in a toy 2D chart is not a measured semantic match.',V)],
pgvector:[
lesson('Exact vector search and approximate indexes','pgvector adds vector types, distance operators and index methods to PostgreSQL. Exact ranking searches eligible candidates; ANN indexes trade some recall for speed.','HNSW uses a navigable graph; IVFFlat partitions vector space and searches selected lists. Metadata filters, dimensions and distance operators affect plan and recall.','CREATE EXTENSION IF NOT EXISTS vector;\nSELECT id,content FROM chunks ORDER BY embedding <=> $1::vector LIMIT 5;','Benchmark exact versus indexed recall, p95 latency, build time and memory for your data. Combine structured filters with similarity where needed.','Creating an ANN index does not guarantee the filtered top K or latency you expect.',V),
lesson('Hybrid retrieval','Keyword search finds literal terminology; vectors can find semantically related phrasing. Combining them can improve coverage.','Rank candidates from text and vector search, then combine or rerank. Keep tenant and access filters enforced before context reaches the model.','-- Conceptual: combine FTS-ranked and vector-ranked candidate ids, then rerank.','Evaluate against a labeled question set; choose the simplest retrieval path meeting quality and latency targets.','Vector search does not replace exact SQL predicates, and lexical search does not understand every paraphrase.',V)],
rag:[
lesson('RAG as visible evidence flow','RAG retrieves context at question time and gives it to a generation model. It does not change model weights.','Ingest and chunk documents, embed chunks, store vectors and metadata, embed the user query, retrieve top K, show chunks, then send selected context with the question to an LLM.','SELECT content,embedding <=> $1::vector AS distance\nFROM chunks ORDER BY embedding <=> $1::vector LIMIT 3;','Measure retrieval quality separately from answer quality. Cite retrieved chunks and reject answers unsupported by context.','Retrieved text is untrusted input and may contain malicious instructions.',V),
lesson('Failure modes of AI retrieval','A fluent answer can be unsupported even when retrieval returns plausible chunks.','Chunking, stale content, metadata filters, model changes, approximate recall and prompt limits can all remove needed evidence. Permissions must hold across the entire pipeline.','-- Inspect chunk ids, source, score and tenant for every answer.','Log retrieval provenance, test no-answer cases and compare with a labeled evaluation set.','Do not hide retrieved chunks behind the answer in a teaching or debugging demo.',V)],
'at-scale':[
lesson('Operate by SLO and bottleneck','Capacity planning starts with workload and a latency/reliability target, not a universal “PostgreSQL can handle N requests” number.','Observe API p95 latency, query p95, CPU, buffer/cache behavior, disk I/O, locks, pool queue wait, replica lag, WAL growth and autovacuum. Change one bottleneck at a time.','SELECT state,wait_event_type,count(*) FROM pg_stat_activity GROUP BY 1,2;','Document backups, restore drills, failover, schema migrations and incident response before adding shards.','Request count alone says little about database work per request.',P+'monitoring-stats.html'),
lesson('Application query patterns','A fast single query can still make an endpoint slow when called once per result row. N+1 reads, unbounded OFFSET and unsafe SQL construction are common application bottlenecks.','Use parameterized statements, batch related reads, paginate with stable ordering and consider keyset pagination for deep pages. Hold a transaction only while its DB work is active.','SELECT id,created_at FROM events\nWHERE (created_at,id) < ($1::timestamptz,$2::bigint)\nORDER BY created_at DESC,id DESC LIMIT 50;','Measure end-to-end p95 and query counts per request. Compare application logs with pg_stat_statements where enabled.','An index cannot repair an endpoint that makes thousands of avoidable round trips or uses unsafe string-built SQL.',P+'queries-limit.html'),
lesson('Safe schema evolution','Schema changes can block work or force backfills. Production migrations should be designed for concurrent application versions.','Add compatible columns, deploy code that can handle old/new shape, backfill in batches, then enforce constraints and remove old fields. Some DDL takes strong locks; CONCURRENTLY index creation has special rules.','CREATE INDEX CONCURRENTLY users_tenant_joined_idx ON users(tenant_id,joined_at);','Test migrations on representative size and set a suitable lock_timeout for operations that must fail rather than queue indefinitely.','A quick migration on an empty development table may be dangerous on a busy production table.',P+'sql-createindex.html')],
recap:[
lesson('Capstone: explain one request end to end','Trace the same request through HTTP, pool, parse/plan, index or scan, row visibility, WAL for writes, page storage and possibly a replica or retrieval pipeline.','For every layer name its input, output, guarantee, resource cost and observable metric. That is a stronger mental model than memorizing feature names.','EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM users WHERE id=42;','Build a small app, seed realistic data, measure a slow query, add a justified index, test concurrent writes and rehearse recovery.','A zero-to-hero course ends when you can explain and measure behavior, not when you recognize terms.',P+'tutorial.html')]
};
for(const [screen,lessons] of Object.entries(advancedCurriculum)){if(!curriculum[screen])throw Error(`Unknown advanced screen: ${screen}`);curriculum[screen].push(...lessons)}
export const studyCount=Object.values(curriculum).reduce((n,items)=>n+items.length,0);
