// Original technical notes for self-study. Primary references are linked in each entry.
export const deepDives={
why:{why:'PostgreSQL fits applications that need related records, constraints, joins and dependable transactions.',how:'A relational schema can enforce primary keys, foreign keys, unique values and checks. SQL combines structured retrieval with JSONB, text search and optional extensions. It is open source under the PostgreSQL License.',production:'Compare against actual workload and operations: a cache, search engine or columnar warehouse may be a better component for a specialized job.',source:'https://www.postgresql.org/about/licence/'},
runtime:{why:'An HTTP request and a SQL query consume resources in different processes, often on different hosts.',how:'The API server runs handlers and business logic. PostgreSQL runs backends, background workers, buffer management and writes table/index files plus WAL to its host storage. PostgreSQL is open source and can be self-hosted.',production:'Size the database with CPU, memory working set, I/O, connection count and latency; size the API separately for request and application work.',source:'https://www.postgresql.org/docs/current/runtime-config-resource.html'},
create:{why:'A database server is software that must run before a client can create or use a database.',how:'Install or start PostgreSQL, connect with psql, use CREATE DATABASE (outside a transaction block), reconnect, CREATE SCHEMA, CREATE TABLE, INSERT and SELECT. A server cluster holds multiple databases; a schema groups objects within one.',production:'Separate a demo database from production and grant only needed rights to application roles. Backups and patching belong to whoever operates the server.',source:'https://www.postgresql.org/docs/current/tutorial-createdb.html'},
data:{why:'Clear names for each layer make SQL and storage easier to understand.',how:'A column is a named typed field; a row is one record; a table groups same-shaped rows. In relational theory a row is a tuple and a column is an attribute. PostgreSQL also uses heap tuple for a physical row version.',production:'Choose types, NOT NULL, keys and checks to encode invariants. A table is not merely a spreadsheet: concurrent transactions and constraints matter.',source:'https://www.postgresql.org/docs/current/tutorial-concepts.html'},
relation:{why:'“Relation” in relational database comes from mathematics; it does not mean only the line between two entity boxes.',how:'In theory a relation is a set of tuples with attributes. SQL tables are the practical implementation but allow duplicates and NULL. A foreign key separately checks a matching referenced key; a JOIN combines matching rows when queried. An FK does not automatically create an index on its referencing columns.',production:'Use primary and foreign keys for integrity, and add indexes based on queries or FK update/delete patterns. Many-to-many relationships use a junction table.',source:'https://www.postgresql.org/docs/current/tutorial-concepts.html'},
relations:{why:'Related tables represent real entities without duplicating every value in every row.',how:'A primary key identifies a row. A foreign key enforces a reference. One-to-many puts an FK on the many side; one-to-one makes that FK unique; many-to-many uses a join table.',production:'Index the referencing FK when joins or parent deletes/updates justify it; constraints protect validity, indexes help access.',source:'https://www.postgresql.org/docs/current/ddl-constraints.html'},
concurrency:{why:'Two writers of the same row cannot both change it independently at the same instant.',how:'An UPDATE creates a new row version and holds a row lock until its transaction ends. A second UPDATE waits and rechecks after release. A normal SELECT uses a snapshot of committed versions and generally does not wait on that row lock. Under READ COMMITTED each statement has a fresh snapshot.',production:'There is no universal transaction duration. Measure transaction age using pg_stat_activity.xact_start and lock waits via pg_stat_activity.wait_event_type, then inspect p95 latency. Keep transactions brief and avoid user/network think time inside them.',source:'https://www.postgresql.org/docs/current/explicit-locking.html'},
views:{why:'A repeated query can be named, and an expensive result can sometimes be precomputed.',how:'CREATE VIEW stores a query definition and reads base data on execution. CREATE MATERIALIZED VIEW stores result rows; REFRESH recomputes them. Materialized views can have indexes but become stale until refreshed.',production:'Plan refresh cost and acceptable staleness. Review permissions and RLS behavior, especially owner privileges and security_invoker views.',source:'https://www.postgresql.org/docs/current/rules-materializedviews.html'},
extensions:{why:'PostgreSQL can add capabilities without every feature living in its core.',how:'CREATE EXTENSION installs an extension’s objects in the current database when server files and permissions permit. Examples: pg_trgm for trigram matching, PostGIS for geography, vector for embeddings.',production:'Check provider support, version compatibility and privileges before relying on an extension. Avoid installing unneeded extensions.',source:'https://www.postgresql.org/docs/current/sql-createextension.html'},
supabase:{why:'Supabase uses PostgreSQL as its data core and supplies product services around it.',how:'PostgREST exposes a database-backed API. Auth creates identities and tokens; database roles and RLS govern rows. Realtime observes changes; Storage uses object files with database metadata; Edge Functions execute outside PostgreSQL; Studio manages objects.',production:'Write and test RLS policies for exposed tables. Views, functions and extension privileges can affect the boundary; inspect each service’s behavior.',source:'https://supabase.com/docs/guides/getting-started/architecture'},
deploy:{why:'Hosting options trade control, operations and resource behavior.',how:'Self-hosting means operating the PostgreSQL process and backups. Neon separates compute from storage and offers autoscaling and scale-to-zero for variable use. RDS provides managed instances and storage choices with backup and availability features.',production:'Start from measured CPU, memory working set, storage IOPS, connections, p95 latency, growth and uptime needs. Load-test before upsizing. Add replicas for read/availability needs; shard only after simpler capacity choices fail.',source:'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.Summary.html'},
architecture:{why:'SQL states the requested result. PostgreSQL still has to choose a physical way to produce it. Parsing and analysis check the statement and resolve names; planning estimates the cost of possible paths; execution runs the selected plan.',how:'A scan may read heap pages sequentially or find candidate tuple locations through an index. Shared buffers cache disk pages. Writes also create WAL records. Buffer hits mean cached blocks were found; they do not mean the query had zero CPU cost.',production:'Inspect the plan and the workload before adding an index. One query plan does not describe the whole system.',source:'https://www.postgresql.org/docs/current/using-explain.html'},
transactions:{why:'A transfer is one logical unit even though it changes two rows. A transaction groups the changes, and a rollback abandons them together.',how:'Atomicity controls all-or-nothing completion. Consistency depends on valid constraints and application invariants. Isolation controls visibility and concurrent effects. Durability concerns committed changes surviving a crash. PostgreSQL supports multiple isolation levels; the choice matters for anomalies.',production:'Keep transactions short. If two transfers update accounts in different order, a deadlock can occur; applications should recognize and retry safe transient errors.',source:'https://www.postgresql.org/docs/current/transaction-iso.html'},
mvcc:{why:'Readers and writers need to coexist without treating every change as an immediate overwrite visible to everyone.',how:'A tuple version has transaction metadata. A snapshot decides whether the creating and deleting transactions make that version visible. UPDATE typically leaves an older version and creates a newer one. The old version cannot be reclaimed until it is no longer needed by relevant snapshots.',production:'Long transactions can keep old versions alive and increase bloat. MVCC does not eliminate locks for conflicting writes or schema operations.',source:'https://www.postgresql.org/docs/current/mvcc-intro.html'},
index:{why:'A selective query may need only a handful of rows from a large table. A B-tree avoids visiting every heap page to find those candidates.',how:'The index stores ordered keys with references to tuples. PostgreSQL may choose an index scan, bitmap scan or sequential scan. A composite index helps only when query predicates and order match a useful prefix. Partial and expression indexes cover narrower patterns.',production:'Every index consumes disk, adds write work and can require maintenance. Check real query plans and update frequency before creating one.',source:'https://www.postgresql.org/docs/current/indexes.html'},
explain:{why:'A slow query is a measurement problem. EXPLAIN exposes the operations PostgreSQL chose; ANALYZE executes them and adds actual observations.',how:'Read plans from the bottom up. Costs are relative planning units, while actual times are milliseconds. `Actual Rows` is emitted per loop. `Rows Removed by Filter` indicates tuples rejected at that node. `BUFFERS` reports block activity, including cache hits and reads.',production:'Run on representative data. `EXPLAIN ANALYZE` really executes the query, so use a safe transaction or replica for modifying statements. Compare before and after using the exact same SQL.',source:'https://www.postgresql.org/docs/current/using-explain.html'},
lab:{why:'The index story is only credible when the query, dataset and measurements are visible.',how:'The local demo creates real users and orders, calls `ANALYZE`, obtains JSON plans with `EXPLAIN (ANALYZE, BUFFERS)`, creates a selected index and reruns the same SQL. Seeding and measurements vary across machines and cache states.',production:'Do not infer a universal speedup factor from one run. The broad filter, JOIN and OFFSET examples show cases where a new index may have little effect or even regress the selected plan.',source:'https://www.postgresql.org/docs/current/using-explain.html'},
vacuum:{why:'MVCC leaves tuple versions that eventually become obsolete. Reusable space and visibility information need ongoing maintenance.',how:'Normal VACUUM identifies removable versions, makes space reusable and updates visibility information. Autovacuum starts work based on activity thresholds and scale factors. ANALYZE refreshes statistics. A long-running transaction may prevent removal.',production:'Check autovacuum activity, dead tuples and old transactions before using VACUUM FULL. FULL rewrites the table and takes an exclusive lock.',source:'https://www.postgresql.org/docs/current/routine-vacuuming.html'},
wal:{why:'Committing every transaction by flushing every changed data page would be inefficient and complicate crash recovery.',how:'PostgreSQL records changes in WAL. WAL required for a committed change is durable before affected data pages must be flushed. After a crash, recovery replays WAL from a checkpoint. Physical replication can stream WAL to replicas.',production:'WAL is not an independent backup. Monitor disk use and archive/replication retention; test restores rather than assuming they work.',source:'https://www.postgresql.org/docs/current/wal-intro.html'},
replication:{why:'Replicas can help serve read traffic and provide a failover target.',how:'A primary emits WAL and physical standbys replay it. In asynchronous operation, a replica can lag. A read routed there may not see a recent write. Failover changes which node accepts writes and requires client routing and operational procedures.',production:'Replication copies mistakes too; it does not replace backups. Measure replay lag and test failover.',source:'https://www.postgresql.org/docs/current/warm-standby.html'},
pool:{why:'A database connection has memory and scheduling cost. Opening one per request can exhaust the server under bursts.',how:'A pool caps concurrent database sessions and queues incoming work. Application pools hold sessions for reuse. PgBouncer can provide session or transaction pooling, but transaction pooling changes assumptions about session state.',production:'Tune with request concurrency, query duration, database resources and queue wait. A bigger pool can increase contention even while reducing queue time.',source:'https://www.postgresql.org/docs/current/runtime-config-connection.html'},
partition:{why:'Partitioning is useful when large tables have a natural key such as time and queries often restrict that key.',how:'A partitioned table routes rows to child relations. Planner or executor pruning can avoid partitions that cannot match the predicate. The predicate, parameterization and partition bounds determine whether pruning works.',production:'Too many partitions increase planning and maintenance overhead. Partitioning remains within one database; sharding distributes data across databases.',source:'https://www.postgresql.org/docs/current/ddl-partitioning.html'},
security:{why:'Application identity alone does not enforce every data boundary. The database can restrict operations and rows.',how:'Roles and grants allow operations; RLS policies add row-level predicates. Table owners and roles with BYPASSRLS may bypass policies. The app must set tenant identity from trusted authentication context, not an unverified request parameter.',production:'Test policies as actual application roles and check their query plans. Keep least-privilege grants even when RLS is enabled.',source:'https://www.postgresql.org/docs/current/ddl-rowsecurity.html'},
pgvector:{why:'Some questions need similarity ranking instead of exact text or structured matching.',how:'pgvector stores vectors as a PostgreSQL type and offers distance operators. Exact search ranks candidate rows; HNSW and IVFFlat approximate nearest neighbors for speed at a possible recall cost. Metadata filters and index configuration affect results.',production:'Benchmark recall, latency, memory and index build time on representative data. Keep model, dimensions and distance metric consistent.',source:'https://github.com/pgvector/pgvector/blob/master/README.md'},
rag:{why:'An LLM may need current or private knowledge outside its training. Retrieval supplies relevant text at answer time.',how:'Chunk documents, generate embeddings, store chunks with metadata, embed the question, rank candidates, inspect top chunks and send them as context with the question to an LLM. Hybrid lexical plus vector retrieval can improve some workloads.',production:'Evaluate retrieval separately from answer quality. Treat retrieved text as untrusted input, keep citations and enforce tenant filtering before context reaches the model.',source:'https://github.com/pgvector/pgvector/blob/master/README.md'}
};
export const myths=[
['More indexes always make PostgreSQL faster.','Indexes can reduce reads, but consume space, slow writes and may be ignored for broad queries.'],
['More connections mean more throughput.','Past a workload-dependent point, additional active queries increase contention and memory pressure.'],
['VACUUM immediately removes every old row.','Versions needed by snapshots remain; normal VACUUM makes eligible space reusable.'],
['Replication is a backup.','Replicas can copy erroneous changes. Keep and test independent backups.'],
['Vector search replaces SQL.','Similarity ranking and structured predicates solve different questions and can be combined.'],
['RAG is fine-tuning.','RAG retrieves context at query time; fine-tuning changes model parameters.']
];
